name: Test examples

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run examples
        run: |
          python main.py examples/hello.san
          python main.py examples/greeting.san
          python main.py examples/narcissus.san
          python main.py examples/iot_demo.san
          python main.py examples/higher_order.san